package ma.elaroui.pos.desktop

enum class DesktopLanguage(val code: String, val rtl: Boolean) {
    FR("fr", false), EN("en", false), AR("ar", true);

    companion object {
        fun from(code: String?) = entries.firstOrNull { it.code == code } ?: FR
    }
}

/** Central desktop strings. Keeping them out of composables prevents mixed-language screens. */
class DesktopStrings(val selected: DesktopLanguage) {
    fun text(fr: String, en: String, ar: String) = when (selected) {
        DesktopLanguage.FR -> fr; DesktopLanguage.EN -> en; DesktopLanguage.AR -> ar
    }

    // General & Navigation
    val refresh get() = text("Actualiser", "Refresh", "تحديث")
    val lock get() = text("Verrouiller / changer", "Lock / switch user", "قفل / تغيير المستخدم")
    val settings get() = text("Réglages", "Settings", "الإعدادات")
    val save get() = text("Enregistrer", "Save", "حفظ")
    val cancel get() = text("Annuler", "Cancel", "إلغاء")
    val edit get() = text("Éditer", "Edit", "تعديل")
    val add get() = text("Ajouter", "Add", "إضافة")
    val activate get() = text("Activer", "Activate", "تفعيل")
    val deactivate get() = text("Désactiver", "Deactivate", "تعطيل")
    val all get() = text("Tous", "All", "الكل")
    val noResults get() = text("Aucun résultat", "No results", "لا توجد نتائج")
    val required get() = text("Champ obligatoire", "Required field", "حقل مطلوب")
    val invalidAmount get() = text("Montant invalide", "Invalid amount", "مبلغ غير صالح")
    val back get() = text("Retour", "Back", "رجوع")
    val backToDashboard get() = text("← Retour au tableau de bord", "← Back to dashboard", "← العودة إلى لوحة التحكم")
    val confirm get() = text("Confirmer", "Confirm", "تأكيد")
    val details get() = text("Détails", "Details", "تفاصيل")
    val delete get() = text("Supprimer", "Delete", "حذف")
    val status get() = text("Statut", "Status", "الحالة")
    val active get() = text("Actif", "Active", "نشط")
    val inactive get() = text("Inactif", "Inactive", "غير نشط")
    val search get() = text("Rechercher", "Search", "بحث")
    val ok get() = text("OK", "OK", "موافق")
    val close get() = text("Fermer", "Close", "إغلاق")
    val total get() = text("Total", "Total", "المجموع")
    val subtotal get() = text("Sous-total", "Subtotal", "المجموع الفرعي")
    val tax get() = text("TVA", "Tax", "الضريبة")
    val discount get() = text("Remise", "Discount", "الخصم")
    val price get() = text("Prix", "Price", "السعر")
    val priceTtc get() = text("Prix TTC", "Price (incl. tax)", "السعر شامل الضريبة")
    val unitPrice get() = text("Prix unitaire", "Unit Price", "سعر الوحدة")
    val currency get() = text("DH", "DH", "د.م.")
    val preview get() = text("Aperçu", "Preview", "معاينة")

    // Setup
    val setupTitle get() = text("Configuration initiale", "Initial Setup", "الإعداد الأولي")
    val ownerName get() = text("Nom du propriétaire", "Owner Name", "اسم المالك")
    val pinCode get() = text("Code PIN (4 à 6 chiffres)", "PIN Code (4 to 6 digits)", "رمز PIN (4 إلى 6 أرقام)")
    val confirmPin get() = text("Confirmer le code PIN", "Confirm PIN", "تأكيد رمز PIN")
    val pinMismatch get() = text("Les codes PIN ne correspondent pas", "PIN codes do not match", "رموز PIN غير متطابقة")
    val pinMinLength get() = text("Le PIN doit contenir 4 à 6 chiffres", "PIN must contain 4 to 6 digits", "يجب أن يتكون رمز PIN من 4 إلى 6 أرقام")
    val duplicatePin get() = text("Ce code PIN est déjà utilisé par un autre utilisateur.", "This PIN is already used by another user.", "رمز PIN هذا مستخدم بالفعل من قبل مستخدم آخر.")
    val duplicateProductError get() = text("Un produit avec ce nom existe déjà dans cette catégorie.", "A product with this name already exists in this category.", "يوجد منتج بهذا الاسم بالفعل في هذه الفئة.")
    val duplicateCategoryError get() = text("Une catégorie avec ce nom existe déjà.", "A category with this name already exists.", "توجد فئة بهذا الاسم بالفعل.")
    val continueAction get() = text("Continuer", "Continue", "متابعة")

    // Auth & Login
    val loginTitle get() = text("Connexion", "Login", "تسجيل الدخول")
    val selectUser get() = text("Sélectionner un utilisateur", "Select User", "اختر مستخدم")
    val enterPin get() = text("Entrez votre code PIN", "Enter PIN", "أدخل رمز PIN")
    val wrongPin get() = text("Code PIN incorrect", "Incorrect PIN", "رمز PIN غير صحيح")
    val ownerRole get() = text("Propriétaire", "Owner", "المالك")
    val cashierRole get() = text("Caissier", "Cashier", "أمين الصندوق")

    // License
    val licenseTitle get() = text("Gestion de Licence", "License Management", "إدارة الترخيص")
    val trialBannerText get() = text("Période d’essai — Il vous reste", "Trial Period — Remaining:", "فترة تجريبية — المتبقي:")
    val days get() = text("jour(s)", "day(s)", "يوم")
    val activateNow get() = text("Activer maintenant", "Activate Now", "تفعيل الآن")
    val installationId get() = text("ID d’installation", "Installation ID", "معرف التثبيت")
    val requestCode get() = text("Code de demande", "Request Code", "رمز الطلب")
    val licenseKey get() = text("Clé de licence", "License Key", "مفتوح الترخيص")
    val copyRequestCode get() = text("Copier le code de demande", "Copy Request Code", "نسخ رمز الطلب")

    // Dashboard
    val dashboardTitle get() = text("Tableau de bord Propriétaire", "Owner Dashboard", "لوحة التحكم للمالك")
    val posSales get() = text("Ventes POS", "POS Sales", "مبيعات POS")
    val activeOrders get() = text("Ventes en attente", "Held Sales", "المبيعات المعلقة")
    val salesHistory get() = text("Historique des ventes", "Sales History", "سجل المبيعات")
    val dailyReport get() = text("Rapport des ventes", "Daily Sales Report", "تقرير المبيعات")
    val productMgmt get() = text("Gestion des produits", "Products Management", "إدارة المنتجات")
    val categoryMgmt get() = text("Gestion des catégories", "Categories Management", "إدارة الفئات")
    val tableMgmt get() = text("Espaces & Tables", "Areas & Tables Management", "إدارة المساحات والطاولات")
    val cashierMgmt get() = text("Gestion des caissiers", "Cashiers Management", "إدارة أمناء الصندوق")
    val registerHistory get() = text("Historique des caisses", "Register Sessions History", "سجل الصناديق")

    // POS & Cart
    val orderType get() = text("Type de commande", "Order Type", "نوع الطلب")
    val dineIn get() = text("Sur place", "Dine In", "في المطعم")
    val takeaway get() = text("À emporter", "Takeaway", "سفري")
    val delivery get() = text("Livraison", "Delivery", "توصيل")
    val selectTable get() = text("Sélectionner une table", "Select Table", "اختر طاولة")
    val tableLabel get() = text("Table", "Table", "طاولة")
    val addToCart get() = text("Ajouter au panier", "Add to Cart", "إضافة إلى السلة")
    val cartTitle get() = text("Panier en cours", "Current Cart", "السلة الحالية")
    val emptyCart get() = text("Votre panier est vide", "Your cart is empty", "السلة فارغة")
    val proceedToPayment get() = text("Procéder au paiement", "Proceed to Payment", "الانتقال إلى الدفع")
    val holdOrder get() = text("Mettre en attente", "Hold Order", "تعليق الطلب")
    val validateOrder get() = text("Valider la vente", "Validate sale", "تأكيد البيع")
    val checkoutOrder get() = text("Addition / Encaisser", "Bill / Checkout", "الفاتورة / التحصيل")
    val outOfStock get() = text("Rupture de stock", "Out of stock", "غير متوفر")
    val itemNotes get() = text("Notes sur l’article", "Item notes", "ملاحظات على العنصر")

    // Active Orders
    val noActiveOrders get() = text("Aucune vente en attente", "No held sales", "لا توجد مبيعات معلقة")
    val resumeOrder get() = text("Reprendre", "Resume", "استئناف")
    val cancelOrder get() = text("Annuler la vente", "Cancel Sale", "إلغاء البيع")
    val cancelReason get() = text("Motif d’annulation obligatoire", "Cancellation reason (required)", "سبب الإلغاء (مطلوب)")
    val moveTable get() = text("Changer de table", "Move Table", "تغيير الطاولة")

    // Payment
    val paymentTitle get() = text("Paiement de la vente", "Sale Payment", "دفع البيع")
    val paymentMethod get() = text("Mode de paiement", "Payment Method", "طريقة الدفع")
    val cash get() = text("Espèces", "Cash", "نقداً")
    val card get() = text("Carte bancaire", "Card", "بطاقة بنكية")
    val amountReceived get() = text("Montant reçu", "Amount Received", "المبلغ المستلم")
    val changeDue get() = text("Monnaie à rendre", "Change Due", "الباقي للزبون")
    val exactAmount get() = text("Montant exact", "Exact Amount", "المبلغ بالضبط")
    val insufficientCash get() = text("Montant insuffisant", "Insufficient amount", "المبلغ غير كافٍ")
    val paymentSuccess get() = text("Paiement effectué avec succès", "Payment Completed Successfully", "تمت عملية الدفع بنجاح")

    // Receipt & Printing
    val customerReceipt get() = text("Reçu client", "Customer Receipt", "إيصال الزبون")
    val kitchenTicket get() = text("Bon de cuisine", "Kitchen Ticket", "تذكرة المطبخ")
    val preparationTicket get() = text("Ticket de préparation", "Preparation Ticket", "تذكرة التحضير")
    val printReceipt get() = text("Imprimer le reçu", "Print Receipt", "طباعة الإيصال")
    val printKitchen get() = text("Imprimer en cuisine", "Print Kitchen Ticket", "طباعة للمطبخ")
    val printPreparation get() = text("Imprimer préparation", "Print Preparation Ticket", "طباعة تذكرة التحضير")

    // Register Sessions
    val openRegisterTitle get() = text("Ouverture de caisse", "Open Register", "فتح الصندوق")
    val openingCash get() = text("Fond de caisse initial", "Opening Cash Balance", "مبلغ فتح الصندوق")
    val openRegisterAction get() = text("Ouvrir la caisse", "Open Register", "فتح الصندوق")
    val currentSessionTitle get() = text("Session de caisse en cours", "Current Register Session", "جلسة الصندوق الحالية")
    val sessionOpenedAt get() = text("Ouverte le", "Opened at", "تم الفتح في")
    val expectedCash get() = text("Espèces attendues", "Expected Cash", "المبلغ المتوقع")
    val cashIn get() = text("Entrée d’espèces", "Cash In", "إدخال سيولة")
    val cashOut get() = text("Sortie d’espèces", "Cash Out", "سحب سيولة")
    val movementReason get() = text("Motif du mouvement", "Movement Reason", "سبب الحركة")
    val configureApprovalPin get() = text("Configurer le PIN des sorties", "Configure withdrawal PIN", "إعداد رمز السحب")
    val closeRegisterTitle get() = text("Fermeture de caisse", "Close Register", "إغلاق الصندوق")
    val countedCash get() = text("Espèces comptées en caisse", "Counted Cash in Drawer", "المبلغ المحسوب في الصندوق")
    val discrepancy get() = text("Écart de caisse", "Cash Discrepancy", "فارق الصندوق")
    val surplus get() = text("Surplus", "Surplus", "فائض")
    val deficit get() = text("Manquant", "Deficit", "عجز")
    val exactMatch get() = text("Conforme (Aucun écart)", "Exact (No discrepancy)", "مطابق (لا يوجد فارق)")
    val closeRegisterAction get() = text("Fermer la caisse", "Close Register", "إغلاق الصندوق")
    val cardSales get() = text("Ventes Carte / TPE", "Card/TPE Sales", "المبيعات بالبطاقة")
    val totalSales get() = text("Ventes totales", "Total Sales", "إجمالي المبيعات")
    val leftInDrawer get() = text("Laissé en fond de caisse (Tiroir)", "Left in drawer (Float)", "المبلغ المتروك في الصندوق")
    val removedAmount get() = text("Montant retiré / Enveloppe", "Amount removed / Envelope", "المبلغ المسحوب / الظرف")
    val remittanceReference get() = text("Réf. Enveloppe / Remise", "Envelope/Remittance ref", "مرجع الظرف / التحويل")
    val remittanceDestination get() = text("Destination des fonds", "Remittance destination", "وجهة الأموال المسحوبة")
    val closingNote get() = text("Note de clôture (facultatif)", "Closing note (optional)", "ملاحظة الإغلاق (اختياري)")
    val activeOrdersBlockClosing get() = text("Impossible de clôturer : des commandes sont encore actives sur cette session.", "Cannot close register: active orders still exist for this session.", "تعذر إغلاق الصندوق: توجد طلبات لا تزال نشطة في هذه الجلسة.")
    val leftPlusRemovedMustEqualCounted get() = text("La somme du montant laissé et du montant retiré doit être égale au montant total compté.", "Sum of amount left and amount removed must equal counted cash.", "مجموع المبلغ المتروك والمبلغ المسحوب يجب أن يساوي المبلغ المحسوب.")
    val suggestedOpeningCash get() = text("Fond suggéré (Session précédente)", "Suggested opening float", "المبلغ المقترح (من الجلسة السابقة)")

    // Management (Products, Categories, Tables, Cashiers)
    val productName get() = text("Nom du produit", "Product Name", "اسم المنتج")
    val priceCentimes get() = text("Prix en DH", "Price in DH", "السعر بالدرهم")
    val taxRate get() = text("Taux de TVA", "Tax Rate", "نسبة الضريبة")
    val category get() = text("Catégorie", "Category", "الفئة")
    val categoryName get() = text("Nom de la catégorie", "Category Name", "اسم الفئة")
    val areaName get() = text("Nom de l’espace", "Dining Area Name", "اسم المساحة")
    val tableName get() = text("Nom de la table", "Table Name", "اسم الطاولة")
    val availableStatus get() = text("Disponible (En stock)", "Available (In stock)", "متوفر في المخزون")
    val unavailableStatus get() = text("Rupture de stock", "Out of stock", "غير متوفر")
    val tableAvailable get() = text("Libre", "Available", "متاحة")
    val tableOccupied get() = text("Occupée", "Occupied", "مشغولة")
    val tableReserved get() = text("Réservée", "Reserved", "محجوزة")
    val cataloguePreview get() = text("Aperçu du catalogue", "Catalogue Preview", "معاينة الكتالوج")
    val logoLabel get() = text("Logo de l’établissement", "Establishment Logo", "شعار المؤسسة")

    // Reports
    val reportsTitle get() = text("Rapports & Statistiques", "Reports & Analytics", "التقارير والإحصائيات")
    val summaryTab get() = text("Résumé", "Summary", "ملخص")
    val salesTab get() = text("Ventes", "Sales", "المبيعات")
    val sessionsTab get() = text("Sessions de caisse", "Register Sessions", "جلسات الصندوق")
    val today get() = text("Aujourd’hui", "Today", "اليوم")
    val yesterday get() = text("Hier", "Yesterday", "الأمس")
    val last7Days get() = text("7 derniers jours", "Last 7 days", "آخر 7 أيام")
    val thisMonth get() = text("Ce mois", "This month", "هذا الشهر")
    val startDate get() = text("Date début", "Start Date", "تاريخ البداية")
    val endDate get() = text("Date fin", "End Date", "تاريخ النهاية")
    val customPeriod get() = text("Période personnalisée", "Custom period", "فترة مخصصة")
    val totalOrders get() = text("Total ventes", "Total Sales", "إجمالي المبيعات")
    val totalRevenue get() = text("Chiffre d’affaires", "Total Revenue", "إجمالي الإيرادات")
    val cashSales get() = text("Ventes espèces", "Cash Sales", "المبيعات نقداً")
    val categoryBreakdown get() = text("Ventes par catégorie", "Sales by Category", "المبيعات حسب الفئة")

    // Settings, Printers, Backup
    val companyInfo get() = text("Établissement et facture", "Establishment & Invoice", "المؤسسة والفاتورة")
    val companyNameLabel get() = text("Nom de l’établissement", "Establishment Name", "اسم المؤسسة")
    val addressLabel get() = text("Adresse", "Address", "العنوان")
    val phoneLabel get() = text("Téléphone", "Phone", "الهاتف")
    val iceLabel get() = text("ICE (15 chiffres)", "ICE (15 digits)", "ICE (15 رقمًا)")
    val taxIdLabel get() = text("Identifiant fiscal (IF)", "Tax Identifier (IF)", "المعرف الضريبي (IF)")
    val rcLabel get() = text("Registre de commerce (RC)", "Commercial Register (RC)", "السجل التجاري (RC)")
    val patenteLabel get() = text("Patente", "Business Tax (Patente)", "الضريبة المهنية")
    val wifiNameLabel get() = text("Nom du réseau Wi-Fi", "Wi-Fi Network Name", "اسم شبكة Wi-Fi")
    val wifiCodeLabel get() = text("Mot de passe Wi-Fi", "Wi-Fi Password", "رمز Wi-Fi")
    val languageLabel get() = text("Langue d’affichage", "Display Language", "لغة العرض")
    val printersTitle get() = text("Imprimantes", "Printers", "الطابعات")
    val customerPrinterLabel get() = text("Imprimante ticket client", "Customer Receipt Printer", "طابعة إيصال الزبون")
    val kitchenPrinterLabel get() = text("Imprimante bon cuisine", "Kitchen Ticket Printer", "طابعة تذكرة المطبخ")
    val paperWidthLabel get() = text("Largeur du papier", "Paper Width", "عرض الورق")
    val testPrintAction get() = text("Imprimer un ticket de test", "Print Test Ticket", "طباعة إيصال تجريبي")
    val backupRestoreTitle get() = text("Sauvegarde & Restauration", "Backup & Restore", "النسخ الاحتياطي والاستعادة")
    val exportBackup get() = text("Exporter une sauvegarde", "Export Backup", "تصدير نسخة احتياطية")
    val restoreBackup get() = text("Restaurer depuis un fichier", "Restore from File", "استعادة من ملف")
    val restoreNotice get() = text("La restauration nécessite un redémarrage de l’application", "Restore requires restarting the application", "تتطلب الاستعادة إعادة تشغيل التطبيق")
}
