package tools.licensegenerator

import org.json.JSONObject
import java.io.File
import java.security.KeyFactory
import java.security.PrivateKey
import java.security.Signature
import java.security.spec.PKCS8EncodedKeySpec
import java.util.Base64
import java.util.Scanner

/**
 * Standalone CLI License Generator Tool
 * Accepts a License Request Code generated by the Android POS app,
 * prompts for customer & validity details, signs the payload using an external EC or RSA private key,
 * and prints out the formatted digitally signed License Key string.
 */
object LicenseGeneratorCli {

    @JvmStatic
    fun main(args: Array<String>) {
        println("==========================================================")
        println("   MOROCCAN POS - OFFICIAL LICENSE GENERATOR (CLI)       ")
        println("==========================================================")

        val configuredPath = args.firstOrNull()?.trim()?.takeIf { it.isNotEmpty() }
            ?: System.getenv("POS_LICENSE_PRIVATE_KEY")?.trim()?.takeIf { it.isNotEmpty() }
        val privateKeyFile = configuredPath?.let(::File)?.takeIf { it.isFile }
            ?: run {
                println("ERROR: Pass the PKCS#8 private-key path as the first argument")
                println("       or set POS_LICENSE_PRIVATE_KEY.")
                return
            }

        val privateKey = try {
            loadPrivateKeyFromPem(privateKeyFile.readText())
        } catch (e: Exception) {
            println("ERROR: Failed to parse private key: ${e.message}")
            return
        }

        val scanner = Scanner(System.`in`)
        print("\nEnter Client License Request Code: ")
        val requestCode = scanner.nextLine().trim()
        if (requestCode.isEmpty()) {
            println("ERROR: License request code cannot be empty.")
            return
        }

        val requestPayload = try {
            val decodedJsonStr = String(Base64.getDecoder().decode(requestCode), Charsets.UTF_8)
            JSONObject(decodedJsonStr)
        } catch (e: Exception) {
            println("ERROR: Invalid or corrupt License Request Code: ${e.message}")
            return
        }

        val appId = requestPayload.optString("appId", "ma.elaroui.generalpos")
        val productId = requestPayload.optString("productId", "GENERAL_POS_V1")
        val installationId = requestPayload.optString("installationId", "")

        if (installationId.isEmpty()) {
            println("ERROR: Request Code does not contain valid installationId.")
            return
        }

        println("\n--- REQUEST DETAILS ---")
        println("Application ID  : $appId")
        println("Product ID      : $productId")
        println("Installation ID : $installationId")
        println("------------------------")

        print("Enter Customer / Restaurant Name: ")
        val customerName = scanner.nextLine().trim().ifEmpty { "Café & Restaurant Client" }

        print("Select License Type [1 = FULL_LIFETIME, 2 = SUBSCRIPTION] (Default: 1): ")
        val typeChoice = scanner.nextLine().trim()
        val licenseType = if (typeChoice == "2") "SUBSCRIPTION" else "FULL_LIFETIME"

        var expirationDateMs: Long? = null
        if (licenseType == "SUBSCRIPTION") {
            print("Enter subscription validity in days (e.g. 365): ")
            val daysStr = scanner.nextLine().trim()
            val days = daysStr.toLongOrNull() ?: 365L
            expirationDateMs = System.currentTimeMillis() + (days * 24 * 60 * 60 * 1000L)
        }

        val issueDateMs = System.currentTimeMillis()
        val licenseId = "LIC-${System.currentTimeMillis().toString().takeLast(6)}"

        val payloadJson = JSONObject().apply {
            put("licenseId", licenseId)
            put("productId", productId)
            put("appId", appId)
            put("installationId", installationId)
            put("customerName", customerName)
            put("issueDateMs", issueDateMs)
            if (expirationDateMs != null) put("expirationDateMs", expirationDateMs)
            put("licenseType", licenseType)
            put("schemaVersion", "1.0")
        }.toString()

        val signatureBytes = signPayload(payloadJson, privateKey)

        val payloadB64 = Base64.getEncoder().encodeToString(payloadJson.toByteArray(Charsets.UTF_8))
        val sigB64 = Base64.getEncoder().encodeToString(signatureBytes)

        val finalLicenseKey = "$payloadB64.$sigB64"

        println("\n==========================================================")
        println("   GENERATED LICENSE KEY (SEND THIS TO THE CLIENT)       ")
        println("==========================================================")
        println(finalLicenseKey)
        println("==========================================================\n")
    }

    fun signPayload(payloadJson: String, privateKey: PrivateKey): ByteArray {
        val algorithm = when (privateKey.algorithm.uppercase()) {
            "EC", "ECDSA" -> "SHA256withECDSA"
            "RSA" -> "SHA256withRSA"
            else -> error("Unsupported private-key algorithm: ${privateKey.algorithm}")
        }
        val sig = Signature.getInstance(algorithm)
        sig.initSign(privateKey)
        sig.update(payloadJson.toByteArray(Charsets.UTF_8))
        return sig.sign()
    }

    fun loadPrivateKeyFromPem(pem: String): PrivateKey {
        val cleaned = pem
            .replace("-----BEGIN PRIVATE KEY-----", "")
            .replace("-----END PRIVATE KEY-----", "")
            .replace("\\s".toRegex(), "")
        val keyBytes = Base64.getDecoder().decode(cleaned)
        val spec = PKCS8EncodedKeySpec(keyBytes)
        return listOf("EC", "RSA").firstNotNullOfOrNull { algorithm ->
            runCatching {
                KeyFactory.getInstance(algorithm).generatePrivate(spec)
            }.getOrNull()
        } ?: error("Unsupported or invalid PKCS#8 private key.")
    }
}
